### ISSUE TITLE
in day 4 you need to fine the  vegetabel data from 1/5/2024 to 30/6/2024

### ISSUE THREAD

**Issue by ombharamadev** [Vishal24102002/ASSIGNMENTS#2]
![image](https://github.com/Vishal24102002/ASSIGNMENTS/assets/150242178/ebd86a7b-c4a6-4883-a1aa-f3d354d6312d)
in day 4 you need to fine the  vegetabel data from 1/5/2024 to 30/6/2024

**Comment by Vishal24102002** [comment]
ok sir sorry i will update it right now
